version: '3'
services:
  extraction:
    build: 
      context: .
      dockerfile: ./extr/Dockerfile
    volumes:
      - shared_data:/app/raw_data
    environment:
      SSH_USERNAME: sofascore_academy
      SSH_PASSWORD: H69qByfVGwkLgezF

  processing:
    build:
      context: .
      dockerfile: ./proc/Dockerfile
    depends_on: 
      extraction:
        condition: service_completed_successfully
    volumes:
      - shared_data:/app/output

  inserting:
    build:
      context: .
      dockerfile: ./insert/Dockerfile
    depends_on: 
      processing:
        condition: service_completed_successfully
    volumes:
      - shared_data:/app
    environment:
      HOST: clickhouse.sofascore.ai
      PORT: 9000
      USERNAME: lkovacevic
      PASSWORD: b9Ea8XzdFr0w6Zo32i4Z
    

volumes:
  shared_data:
